name: R-CMD-check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: windows-latest  # You specified Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: |
          remotes::install_local(".")
        shell: Rscript {0}

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2

      - name: Run tests
        run: |
          library(testthat)
          test_check("TripadvisoR")
        shell: Rscript {0}
