name: R-CMD-check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: windows-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}  # Load API key for TripAdvisor API
      GITHUB_PAT: ${{ secrets.GH_PAT }}  # Use GitHub PAT for installing packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages(c("rcmdcheck", "rmarkdown", "knitr"))
        shell: Rscript {0}

      - name: Install package with authentication
        run: |
          remotes::install_github("JKiran4/TripadvisoR", auth_token = Sys.getenv("GITHUB_PAT"))
        shell: Rscript {0}

      - name: Build vignettes
        run: |
          devtools::build_vignettes()
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Run tests with API key
        run: |
          Sys.setenv(API_KEY = Sys.getenv("API_KEY"))  # Set API key in R
          library(testthat)
          test_check("TripadvisoR")
        shell: Rscript {0}

      - name: Upload check results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check
