name: R-CMD-check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: windows-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}  # Load API_KEY from GitHub Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc (for vignettes)
        run: choco install pandoc

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages(c("rcmdcheck", "rmarkdown", "knitr"))  # Ensure vignette support
        shell: Rscript {0}

      - name: Install package
        run: |
          remotes::install_local(".")
        shell: Rscript {0}

      - name: Build vignettes
        run: |
          devtools::build_vignettes()
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Run tests with API key
        run: |
          Sys.setenv(API_KEY = Sys.getenv("API_KEY"))  # Set API_KEY in R
          library(testthat)
          test_check("TripadvisoR")
        shell: Rscript {0}

      - name: Upload check results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: R-CMD-check-results
          path: check
